name: Trigger Remote Workflows

on:
  push:
    branches: [main]

env:
  TRIGGER_TOKEN: ${{ secrets.TRIGGER_TOKEN }}

jobs:
  load-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-targets.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - name: Install yq & jq
        run: |
          sudo apt-get update
          sudo apt-get install -y yq jq

      - name: Read targets from config file
        id: set-targets
        shell: bash
        run: |
          echo "Trigger targets:"
          cat trigger-targets.yml
          MATRIX_JSON=$(yq -j '.' trigger-targets.yml | jq -c '.')
          echo "matrix=${MATRIX_JSON}" >> "$GITHUB_OUTPUT"

  fanout:
    needs: load-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.load-matrix.outputs.matrix) }}
    steps:
      - name: Trigger remote workflow
        id: trigger-target
        shell: bash
        run: |
          REPO="${{ matrix.repo }}"
          WORKFLOW="${{ matrix.workflow_filename }}"
          BRANCH="${{ matrix.branch }}"

          echo "Triggering ${REPO}/${WORKFLOW} on branch ${BRANCH}"

          curl -sS -X POST \
            -H "Authorization: token ${TRIGGER_TOKEN}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${REPO}/actions/workflows/${WORKFLOW}/dispatches" \
            -d "{\"ref\":\"${BRANCH}\"}"

      - name: Wait for completion
        shell: bash
        run: |
          REPO="${{ matrix.repo }}"
          WORKFLOW="${{ matrix.workflow_filename }}"
          BRANCH="${{ matrix.branch }}"

          echo "Looking for latest run..."
          RUN_ID=""
          ATTEMPTS=0
          MAX_ATTEMPTS=60
          while [[ -z "$RUN_ID" && $ATTEMPTS -lt $MAX_ATTEMPTS ]]; do
            RUN_ID=$(
              curl -sS \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: token ${TRIGGER_TOKEN}" \
                "https://api.github.com/repos/${REPO}/actions/workflows/${WORKFLOW}/runs?event=workflow_dispatch&branch=${BRANCH}" \
              | jq -r '.workflow_runs | sort_by(.created_at) | reverse | (.[0].id // empty)'
            )
            [[ -z "$RUN_ID" ]] && sleep 2
            ((ATTEMPTS++))
          done

          if [[ -z "$RUN_ID" ]]; then
            echo "ERROR: Run not found"
            exit 1
          fi

          echo "Waiting for completion of run $RUN_ID..."
          STATUS=""
          CONCLUSION=""
          while true; do
            read -r STATUS CONCLUSION < <(
              curl -sS \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: token ${TRIGGER_TOKEN}" \
                "https://api.github.com/repos/${REPO}/actions/runs/${RUN_ID}" \
              | jq -r '.status + " " + ( .conclusion // "" )'
            )
            echo "Status: $STATUS  Conclusion: $CONCLUSION"
            [[ "$STATUS" == "completed" ]] && break
            sleep 10
          done

          echo "Final conclusion: $CONCLUSION"
          if [[ "$CONCLUSION" != "success" ]]; then
            exit 1
          fi
