name: Trigger Remote Workflows (Artifacts way)

on:
  workflow_dispatch:
    inputs:
      environment-name:
        description: 'deploy env'
        required: true
        default: test
        type: choice
        options:
          - test
          - prod
  push:
    paths:
      - 'trigger-targets.yml'

env:
  TRIGGER_TOKEN: ${{ secrets.TRIGGER_TOKEN }}
  VARS_TOKEN: ${{ secrets.VARS_TOKEN }}
  ENVIRONMENT_NAME: ${{ inputs.environment-name }}
  CONFIGS_SAVE_PATH: .orchestrator-configs

jobs:
  load-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-targets.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - name: Install yq & jq
        run: |
          sudo apt-get update
          sudo apt-get install -y yq jq

      - name: Read targets from config file
        id: set-targets
        shell: bash
        run: |
          echo "Trigger targets:"
          cat trigger-targets.yml
          MATRIX_JSON=$(yq -j '.' trigger-targets.yml | jq -c '.')
          echo "matrix=${MATRIX_JSON}" >> "$GITHUB_OUTPUT"

  fanout:
    needs: load-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.load-matrix.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload config artifacts
        id: upload_config_artifacts
        uses: ./.github/actions/upload_config_artifacts
        with:
          service_name: ${{ matrix.name }}
          env_name: ${{ env.ENVIRONMENT_NAME }}
          config_variables_json: ${{ toJson(matrix.config_variables) }}

      - name: Trigger remote workflow (composite)
        id: trigger-target-artifact
        uses: ./.github/actions/trigger_remote_workflow
        with:
          token:               ${{ env.TRIGGER_TOKEN }}
          target_repo:         ${{ matrix.repo }}
          event_type:          import-from-orchestrator
          branch:              ${{ matrix.branch }}
          workflow_filename:   ${{ matrix.workflow_filename }}
          source_owner:        ${{ github.repository_owner }}
          source_repo:         ${{ github.event.repository.name }}
          artifact_name_files: ${{ steps.upload_config_artifacts.outputs.artifact_name_files }}
          artifact_name_vars:  ${{ steps.upload_config_artifacts.outputs.artifact_name_vars }}
          run_id:              ${{ steps.upload_config_artifacts.outputs.run_id }}
          save_path:           ${{ env.CONFIGS_SAVE_PATH }}
