name: Trigger Remote Workflows (Artifacts way)

on:
  workflow_dispatch:
    inputs:
      environment-name:
        description: 'deploy env'
        required: true
        default: test
        type: choice
        options:
          - test
          - prod
  push:
    paths:
      - 'trigger-targets.yml'

env:
  TRIGGER_TOKEN: ${{ secrets.TRIGGER_TOKEN }}
  VARS_TOKEN: ${{ secrets.VARS_TOKEN }}
  ENVIRONMENT_NAME: ${{ inputs.environment-name }}
  CONFIGS_SAVE_PATH: .orchestrator-configs

jobs:
  load-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-targets.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - name: Install yq & jq
        run: |
          sudo apt-get update
          sudo apt-get install -y yq jq

      - name: Read targets from config file
        id: set-targets
        shell: bash
        run: |
          echo "Trigger targets:"
          cat trigger-targets.yml
          MATRIX_JSON=$(yq -j '.' trigger-targets.yml | jq -c '.')
          echo "matrix=${MATRIX_JSON}" >> "$GITHUB_OUTPUT"

  fanout:
    needs: load-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.load-matrix.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload config artifacts
        id: upload_config_artifacts
        uses: ./.github/actions/upload_config_artifacts
        with:
          service_name: ${{ matrix.name }}
          env_name: ${{ env.ENVIRONMENT_NAME }}
          config_variables_json: ${{ toJson(matrix.config_variables) }}

      - name: Trigger remote workflow
        id: trigger-target-artifact
        shell: bash
        run: |
          set -euo pipefail
          REPO="${{ matrix.repo }}"
          SOURCE_OWNER="${{ github.repository_owner }}"
          SOURCE_REPO="${{ github.event.repository.name }}"
          WORKFLOW="${{ matrix.workflow_filename }}"
          BRANCH="${{ matrix.branch }}"
          ARTIFACT_NAME_FILES="${{ steps.upload_config_artifacts.outputs.artifact_name_files }}"
          ARTIFACT_NAME_VARS="${{ steps.upload_config_artifacts.outputs.artifact_name_vars }}"
          RUN_ID="${{ steps.upload_config_artifacts.outputs.run_id }}"
          SAVE_PATH="${{ env.CONFIGS_SAVE_PATH }}"

          echo "Triggering ${REPO}/${WORKFLOW} on branch ${BRANCH}"
          
          payload=$(printf '{"event_type":"import-from-orchestrator","client_payload":{"branch":"%s","workflow_filename":"%s","source_repo":"%s", "source_owner":"%s", "artifact_name_files":"%s", "artifact_name_vars":"%s", "run_id":"%s", "save_path":"%s"}}' \
          "${BRANCH}" "${WORKFLOW}" "${SOURCE_REPO}" "${SOURCE_OWNER}" "${ARTIFACT_NAME_FILES}" "${ARTIFACT_NAME_VARS}" "${RUN_ID}" "${SAVE_PATH}")

          curl -sS -f -X POST \
            -H "Authorization: Bearer ${TRIGGER_TOKEN}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${REPO}/dispatches" \
            -d "${payload}"
